name: Upload templates to GCS

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.10'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Install dependencies for python scripts
        run: pip install -r scripts/requirements.txt
      - name: Upload artifacts to GCS
        run: python scripts/upload-templates.py
