name: Upload templates to GCS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Install dependencies for python scripts
        run: pip install -r scripts/requirements.txt
      - name: Upload artifacts to GCS
        run: python scripts/upload-templates.py
